name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.14', '1.15', '1.16' ]
    name: Test on Go ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go test ./...

  coverage:
    name: test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint

    - name: Run vet & lint
      run: |
        go vet ./...
        golint ./...

    - name: Test
      run: go test -v -covermode=count -coverprofile=coverage.out ./...

    - name: Convert coverage
      uses: jandelgado/gcov2lcov-action@v1.0.5

    - name: Coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: coverage.lcov
