name: Review

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Test on Go 1.18
    runs-on: ubuntu-latest
    steps:
  
    - name: Set up Go 1.18
      uses: actions/setup-go@v2
      with:
        go-version: ^1.18

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        go version
        go install github.com/reviewdog/reviewdog/cmd/reviewdog@latest
        go install golang.org/x/lint/golint@latest

    - name: Run reviewdog
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        reviewdog -reporter=github-pr-check
